### ISSUE TITLE
Please update to clarify 

### ISSUE THREAD

**Issue by lukamun** [NetAppDocs/storagegrid-116#10]
Page: [Shut down grid node](https://docs.netapp.com/us-en/storagegrid-116/maintain/shutting-down-grid-node.html)

change from
To ensure you can access all objects when **a Storage Node is** shut down, stop ingesting objects at a site for approximately one hour before shutting down the node.

to Storage Nodes are

**Comment by netapp-madkat** [comment]
Thank you, Luke, for your comment.  

As we discussed in chat, that whole section was a bit convoluted, so I'm suggesting this rewrite:

"If you plan to shut down more than one Storage Node at a site, stop ingesting objects at that site for approximately one hour before shutting down the nodes.

If any ILM rule uses the **Dual commit** ingest option (or if a rule uses the **Balanced** option and all required copies cannot be created immediately), StorageGRID immediately commits any newly ingested objects to two Storage Nodes on the same site and evaluates ILM later. If more than one Storage Node at a site is shut down, you might not be able to access newly ingested objects for the duration of the shutdown. Write operations might also fail if too few Storage Nodes remain available at the site."

We can add this to the next update for 11.6 doc site. It will also appear in 11.7.

**Comment by netapp-madkat** [comment]
The change to https://docs.netapp.com/us-en/storagegrid-116/maintain/shutting-down-grid-node.html is now live.
