### ISSUE TITLE
Requirements for virtual machines that use NetApp AFF storage: change AFF to Ontap

### ISSUE THREAD

**Issue by lukamun** [NetAppDocs/storagegrid-116#12]
Page: [Storage and performance requirements](https://docs.netapp.com/us-en/storagegrid-116/vmware/storage-and-performance-requirements.html)

**Comment by netapp-madkat** [comment]
Hi, 

The requested changes have been made and are now available on storagegrid-116. Thank you again for your feedback.

Kathy
