### ISSUE TITLE
Suggestion to include pre-upgrade check reference page with list of checks and recommendations / troubleshooting steps

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#14]
Page: [StorageGRID 11.6 Documentation](https://docs.netapp.com/us-en/storagegrid-116/index.html)

Example of pre-upgrade check failures:

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/StorageGRID_11.7_upgrade_precheck_reports_CIFS_audit_warnings

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp 

I've now added links to the precheck KB to the upgrade guide in a couple of places (Obtain required materials and within Perform upgrade instructions). These will apply to the next release; we'll update the current release's content as time allows.

Thank you for your suggestion.

Kathy
