### ISSUE TITLE
Please update the instructions to include default subnet information. 

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-116#15]
Page: [Verify Fibre Channel HBA to replace](https://docs.netapp.com/us-en/storagegrid-116/sg6000/verifying-fibre-channel-hba-to-replace.html)

**Comment by netapp-madkat** [comment]
Hi Jamie,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
closed because we never received more details to make doc changes.
