### ISSUE TITLE
Include information about how to identify secured drives in the controller replacement section of the SG5700 document

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-116#16]
Page: [Replace E5700SG controller](https://docs.netapp.com/us-en/storagegrid-116/sg5700/replacing-e5700sg-controller.html)

**Comment by netapp-madkat** [comment]
Hi Jamie,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-pcelmer** [comment]
Hi Jamie, I have spoke with engineering and the compute controller in the SG5700 can be replaced without unlocking the secured drives. It is only when replacing the E2800 controller that the secured drives need to be unlocked, and we do have instructions in the guide about that situation.
