### ISSUE TITLE
Additional Clarity On Steps

### ISSUE THREAD

**Issue by clhouck25** [NetAppDocs/storagegrid-116#17]
Page: [Investigate lost objects](https://docs.netapp.com/us-en/storagegrid-116/monitor/investigating-lost-objects.html)

Customer has requested additional clarity on steps to specify which node type should be accessed. 

For the audit log messages a admin node and storage node for the ade search

**Comment by netapp-madkat** [comment]
Hi @clhouck25 ,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @clhouck25,

We have created a Mantis for this issue and it is scheduled to be addressed in a future StorageGRID release.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)
