### ISSUE TITLE
Additional Clarity On Steps

### ISSUE THREAD

**Issue by clhouck25** [NetAppDocs/storagegrid-116#18]
Page: [Search for and restore potentially lost objects](https://docs.netapp.com/us-en/storagegrid-116/monitor/searching-for-and-restoring-potentially-lost-objects.html)

Customer requested additional clarification on steps in the document. Specify what node type for steps. 

Admin node for the audit log review. 

Storage node for the ade search.

**Comment by netapp-madkat** [comment]
Hi @clhouck25 ,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @clhouck25,

We have created a Mantis for this issue and it is scheduled to be addressed in a future StorageGRID release.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)
