### ISSUE TITLE
All Earlier versions of StorageGrid doc links are broken

### ISSUE THREAD

**Issue by kyng-codeops** [NetAppDocs/storagegrid-116#19]
On Page: [StorageGRID 11.6 Documentation](https://docs.netapp.com/us-en/storagegrid-116/index.html)

Trying to view "Earlier versions" are broken links for version 11.5 and 11.4. The following links are broken:

https://docs.netapp.com/sgws-115/index.jsp
https://docs.netapp.com/sgws-114/index.jsp

They all redirect to:
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023

Regardless if I'm logged-in to mysupport.netapp.com, those links constantly redirect to a page that says "WARNING: YOUR SEARCH IS LIMITED UNTIL YOU REGISTER AND LOG IN!"

**Comment by netapp-lhalbert** [comment]
Hi, @kyng-codeops,

Thank you for bringing this to our attention. I will reply in more detail within 24 hours.

Thanks again for helping us improve the quality of our documentation.

Lisa C. Halbert
Sr. Technical Writer
StorageGRID Information Engineering (IE)

**Comment by netapp-lhalbert** [comment]
Hi again, @kyng-codeops,

The Documentation Centers have all been either replaced with new GitHub-based sites or with PDFs. For StorageGRID 11.3, 11.4, and 11.5, the Documentation Center URLs were redirected to the NetApp support site (https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023), where you can download the PDFs. 

Other than Release Notes, the PDFs are available without logging in. 

I spoke with one of our admins, @ntap-bmegan, who said that you should see only the one redirect for any link, regardless of your login state. However, the warning banner will persist as you navigate the site. 

We'll update this page to make the link targets more clear.

Thanks again for helping us improve the quality of our documentation.

Lisa C. Halbert
Sr. Technical Writer
StorageGRID Information Engineering (IE)

**Comment by kyng-codeops** [comment]
Hi and thanks for the explanation.
Do you change the documentation URLs every time a new version of code is released? We link to sections of documentation on outside to make re-finding certain content easier. It also breaks simple browser bookmarks when you take down html and convert to PDFs. Why PDFs? PDF files aren’t even mobile friendly.

**Comment by ntap-bmegan** [comment]
Hi, @kyng-codeops! 

NetApp product documentation systems are required to meet updated information security standards. In preparation for shutting off systems that don’t meet requirements, most content has been migrated to GitHub. In cases where migration was not feasible, documents have been preserved in PDF form, with redirects to where the PDFs can be downloaded.

**Comment by netapp-lhalbert** [comment]
@kyng-codeops, to answer your question about whether we change the documentation URLs every time a new version of code is released: Yes, that is our practice. The latest documentation site for StorageGRID is GitHub-based and can be found here: https://docs.netapp.com/us-en/storagegrid-116/

A new feature that the GitHub-based doc sites provide is a version selector so you can easily switch between doc sites for different release versions. For example:
https://docs.netapp.com/us-en/e-series-santricity/index.html or https://docs.netapp.com/us-en/snapcenter/index.html

The version selector is in the upper right corner.

Thanks again for helping us improve the quality of our documentation.
