### ISSUE TITLE
Wrong seperator used for volume range exampe

### ISSUE THREAD

**Issue by sndstone** [NetAppDocs/storagegrid-116#20]
Page: [Restore object data to storage volume, if required](https://docs.netapp.com/us-en/storagegrid-116/maintain/restoring-object-data-to-storage-volume-if-required.html)

The seperator for the volume range example should be , seperated instead of -
repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003-0009 > repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009

**Comment by netapp-madkat** [comment]
Hi @sndstone ,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Lead technical writer
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @sndstone ,

Thank you again for bringing this to our attention. We  verified your request and have now updated that topic to use a comma as the separator. The example now says: --volume-range 0003,0009.  

Please let us know if you notice anything else.

Thanks,

Kathy Maddox
Lead technical writer
StorageGRID Information Engineering (IE)
