### ISSUE TITLE
Procedure to replace FC HBA does not provide the steps to shutdown the appliance

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-116#24]
Page: [Remove Fibre Channel HBA](https://docs.netapp.com/us-en/storagegrid-116/sg6000/removing-fibre-channel-hba.html)

The Procedure to replace FC HBA does not provide the steps to shutdown the appliance. We need to provide a procedure on how to shutdown or at least link another chapter.

regards
Siegfried Hepp - Netapp

**Comment by netapp-perveilerk** [comment]
Hi Siegfried,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kevin Perveiler
StorageGRID IE

**Comment by netapp-madkat** [comment]
Hi @siegfried-h, 

Thank you again for bringing this to our attention. 

The missing step to shut down the node was also reported in https://github.com/NetAppDocs/storagegrid-116/issues/36. We have just updated the topic as requested for the next release of the StorageGRID doc site. We'll will make the same changes to the 11.6 doc site as time allows.

Please let us know if you have any questions or concerns,

Kathy
StorageGRID Information Engineering

**Comment by netapp-madkat** [comment]
Hi @siegfried-h 

We have now made the same change to the StorageGRID 11.6 doc site. Thank you again for helping us to improve our content.

Kathy
