### ISSUE TITLE
SFP Maintenance Page

### ISSUE THREAD

**Issue by hcameron25** [NetAppDocs/storagegrid-116#26]
Page: [StorageGRID 11.6 Documentation](https://docs.netapp.com/us-en/storagegrid-116/index.html)

Customer requested a SFP Maintenance Page about how to handle SFP Maintenance for the various StorageGRID appliance models.

**Comment by netapp-madkat** [comment]
Hi @hcameron25,

Thank you for bringing this to our attention. I have opened a StorageGRID Mantis to track this request. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @hcameron25 

Can you please provide some more specific details about what your customer is requesting? We don't know how to address your request. Do you have an example of the type of SFP maintenance procedures the customer is trying to perform or the issues they are having?

Thanks,

Kathy

**Comment by netapp-madkat** [comment]
@netapp-chandaj I never got more information so we don't know how to address the request. Closing this request now
