### ISSUE TITLE
Differences between SG5712 and SG5712X / SG5760/SG5760X

### ISSUE THREAD

**Issue by ntap-leeray** [NetAppDocs/storagegrid-116#29]
Page: [StorageGRID SG5700 appliance overview](https://docs.netapp.com/us-en/storagegrid-116/sg5700/index.html)
![Screenshot 2023-01-12 115058](https://user-images.githubusercontent.com/39366639/211971633-70e023f9-84a6-4bfc-83c5-4afb658d711f.jpg)

One of these two sentences should refer to SG5760/SG5760X instead of both referring to SG5712/SG5712X.

"There are no specification or functional differences between the _**SG5712 and SG5712X**_ except for the location of the interconnect ports on the storage controller. Similarly, there are no specification or functional differences between the _SG5712 and SG5712X_ except for the location of the interconnect ports on the storage controller."

**Comment by netapp-lhalbert** [comment]
Hi, @ntap-leeray,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Lisa Halbert
Sr. Technical Writer
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @ntap-leeray 

This issue has now been fixed on the StorageGRID 11.6 doc site. Thank  you again for bringing this to our attention.

Kathy
