### ISSUE TITLE
SG6060 Do not support 100MBps

### ISSUE THREAD

**Issue by sndstone** [NetAppDocs/storagegrid-116#31]
Page: [Configure network links (SG6000 series)](https://docs.netapp.com/us-en/storagegrid-116/sg6000/configuring-network-links-sg6000.html)

Please add additional details regarding the inability to use 10 and 100Mbps networks. only 1GBE networks are supported on the MTC / admin network ports.

**Comment by netapp-lhalbert** [comment]
Hi, @sndstone,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Lisa Halbert
Sr. Technical Writer
StorageGRID Information Engineering (IE)

**Comment by netapp-lhalbert** [comment]
@netapp-chandaj: No update yet.

**Comment by netapp-lhalbert** [comment]
@sndstone: We are closing this issue with no change required. Here's the explanation from our SME:

- We clearly state the network speed limitations where we discuss cabling the appliance:
- https://docs.netapp.com/us-en/storagegrid-116/sg6000/cabling-appliance-sg6000.html#cable-the-sgf6024
 
- Connecting cables is the appropriate location to discuss which type of network to connect to, not where you configure port speeds.

Thanks again for  your comments.
