### ISSUE TITLE
Consistency controls

### ISSUE THREAD

**Issue by mzemendoza** [NetAppDocs/storagegrid-116#32]
Page: [Consistency controls](https://docs.netapp.com/us-en/storagegrid-116/s3/consistency-controls.html)

Link 1 – outdated NetApp StorageGrid documentation
 
https://docs.netapp.com/us-en/storagegrid-116/s3/consistency-controls.html#consistency-controls
 
This states that
 

(Default) Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Most closely matches Amazon S3 consistency guarantees.
Which is not the case anymore.
 
Links 2 and 3 – Amazon documentation about the current consistency guarantees
 
https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel

**Comment by netapp-lhalbert** [comment]
Hi, @mzemendoza,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Lisa Halbert
Sr. Technical Writer
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @mzemendoza 

This issue has now been addressed on the StorageGRID 11.6 doc site. Thank you again for letting us know.

Kathy
Principal Technical Writer
StorageGRID Information Engineering (IE)
