### ISSUE TITLE
Process is missing step to stop all services

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#35]
Page: [Shut down SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/shutting-down-sg6000-cn-controller.html)

The process to shut down does not include steps to stop running services. The steps to shut down services are covered in the below page but missing from the shut down procedure.

https://docs.netapp.com/us-en/storagegrid-116/maintain/stopping-server-manager-and-all-services.html

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp, 

Thank you for your request. We confirmed with dev that the steps in the controlled shutdown procedure (https://docs.netapp.com/us-en/storagegrid-116/sg6000/shutting-down-sg6000-cn-controller.html) already cover stopping the services. Performing the steps in https://docs.netapp.com/us-en/storagegrid-116/maintain/stopping-server-manager-and-all-services.html is not needed.

Please let us know if you are seeing something different.

Thanks,

Kathy
Content architect
StorageGRID Information Engineering

**Comment by ahmadm-netapp** [comment]
Hi Kathy @netapp-madkat 

There is no explicit step to stop services (i.e service servermanager stop). Can you please clarify if Dev is stating that it is ok to just run (shutdown -h now) to terminate services and halt the node?

Regards,
Ahmad

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp,

Yes, Dev confirms that it is ok to just run shutdown -h now to terminate services and halt the node. 

Kathy
