### ISSUE TITLE
Provide information regarding part number details and images

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-116#37]
Page: [Replace SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/replacing-sg6000-cn-controller.html)

I received the following feedback from one of our TPM partners:

TPM replaced SG6000-CN with SG100 because of TSE parts order error.
Unfortunately, TPM didn't notice the error because part number wasn't presented on the nodes.
We can find only "node type" on the nodes.
It would be better if we can define the method of part number confirmation with photos or detail explanation.

**Comment by JamieLove-Net2** [comment]
Any updates available on the request to have part numbers or other visual details provided in the instructions?

**Comment by netapp-madkat** [comment]
Hi @JamieLove-Net2 

Thank you for your request. I have created a StorageGRID bug request to track your suggestions.

Thanks,

Kathy Maddox
Principal technical writer
StorageGRID information engineering
