### ISSUE TITLE
Making it more obvious that traffic classification limits are set on a per load balancer basis

### ISSUE THREAD

**Issue by ntap-leeray** [NetAppDocs/storagegrid-116#38]
Page: [Manage traffic classification policies](https://docs.netapp.com/us-en/storagegrid-116/admin/managing-traffic-classification-policies.html)

![image](https://user-images.githubusercontent.com/39366639/219515692-cc61be14-15c3-4c30-ad74-a7866c42e9dc.png)

This information is already in the document but I'd argue that it's not in the most obvious location. I'd suggest adding it here:
![Screenshot 2023-02-17 08 07 34](https://user-images.githubusercontent.com/39366639/219516007-57800e17-b67e-4231-b5b1-360fbbd138bf.png)

and slight change the wordings to make it more obvious:
Optionally, you can set limits for a policy based on the following parameters. These parameters are applied to all load balancers and the limit values are calculated on a per load balancer basis. If traffic is distributed simultaneously across multiple load balancers, the total maximum rates are a multiple of the rate limits you specify.

**Comment by netapp-madkat** [comment]
Hi @ntap-leeray 

Thank you for your suggestions. We've made your requested changes to the next version of the StorageGRID doc site, and we will update the 11.6 doc site as time allows.

As always, we appreciate your help in improving the quality of StorageGRID documentation. 

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @ntap-leeray,

We've now made your requested changes to the 11.6 doc site.

Thank you again for your suggestion,

Kathy
