### ISSUE TITLE
Update screenshot and order of some steps

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#39]
Page: [Change node console passwords](https://docs.netapp.com/us-en/storagegrid-116/admin/change-node-console-password.html)

Step 1 in "Change node console passwords" is a popup that appears as a confirmation for step 3 in "Download the current Recovery Package" section. 

Additionally, the screenshot in the aforementioned step 1 does not match what's in 11.6 today. I can provide actual screenshot offline. But the popup states "Start changing passwords?" instead of what's currently documented "Start node console passwords change".

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp 

Thank you for your comments. I worked with a developer to review the 11.6 change node console procedure against the 11.6 topic, and I agree that what we have is confusing. After performing the procedure a couple of times, I've made some subtle changes to the documentation for our next release. For example, I moved selecting **Yes** on the confirmation popup to the next section as you suggested and I removed the confusing screenshot. 

As time and resources allow, we will make the same changes to the 11.6 doc site.

Hope this helps. Thanks again for your suggestions,

Kathy Maddox
Principal Technical Writer
StorageGRID Information Engineering

**Comment by ahmadm-netapp** [comment]
Hi Kathy,

Thank you for the updates. I will check out the 11.7 documentation once it becomes available.

Regards,
Ahmad

From: Kathy Maddox ***@***.***>
Date: Wednesday, March 8, 2023 at 6:32 PM
To: NetAppDocs/storagegrid-116 ***@***.***>
Cc: Moubarak, Ahmad ***@***.***>, Mention ***@***.***>
Subject: Re: [NetAppDocs/storagegrid-116] Update screenshot and order of some steps (Issue #39)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi @ahmadm-netapp<https://github.com/ahmadm-netapp>

Thank you for your comments. I worked with a developer to review the 11.6 change node console procedure against the 11.6 topic, and I agree that what we have is confusing. After performing the procedure a couple of times, I've made some subtle changes to the documentation for our next release. For example, I moved selecting Yes on the confirmation popup to the next section as you suggested and I removed the confusing screenshot.

As time and resources allow, we will make the same changes to the 11.6 doc site.

Hope this helps. Thanks again for your suggestions,

Kathy Maddox
Principal Technical Writer
StorageGRID Information Engineering

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp, 

We have now updated the topic in the 11.6 doc site.  See https://docs.netapp.com/us-en/storagegrid-116/admin/change-node-console-password.html. 

Thank you again for bringing this to our attention.

Kathy

**Comment by ahmadm-netapp** [comment]
Thank you @netapp-madkat  for the updates. It looks good now.
