### ISSUE TITLE
Recommendation for bucket consistency level is not strong enough

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-116#40]
Page: [Other best practices for StorageGRID and FabricPool](https://docs.netapp.com/us-en/storagegrid-116/fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html)

Hi the docs says:
For FabricPool buckets, the recommended bucket consistency level is “read-after-new-write.” The “available” consistency level is not recommended

Using the "available" consistency level cause data corruption! Because of this the wording "not recommended" to too week.

I suggest:
Do not use the available consistency level for buckets used as FabricPool targets.

Please also change the 11.5 documentation:
https://docs.netapp.com/us-en/storagegrid-115/fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html

**Comment by netapp-madkat** [comment]
Hi @siegfried-h,

The change you requested is now live on the 11.6 site (and it will appear in the next StorageGRID doc site as well). Thank you again for bringing this to our attention.

kathy
