### ISSUE TITLE
Include guidance on how to move data away from a cloud storage pool

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/storagegrid-116#41]
Page: [Considerations for Cloud Storage Pools](https://docs.netapp.com/us-en/storagegrid-116/ilm/considerations-for-cloud-storage-pools.html)

It would be helpful to see some information on the best practices / correct order of steps to move data on a cloud storage pool back to the local storage pool on the local SGrid so that the cloud storage pool can be removed.

**Comment by netapp-madkat** [comment]
Hi @roscocheeta,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Principal technical writer
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @roscocheeta 

We have now added instructions for "Use ILM to move object data" to the instructions for Removing a Cloud Storage Pool.  We've made the change for the upcoming StorageGRID release. We will update the 11.6 topic as time allows.

Thank you again for your suggestion and for helping us to improve the docs.

Kathy
