### ISSUE TITLE
Missing external comms

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/storagegrid-116#42]
Page: [External communications](https://docs.netapp.com/us-en/storagegrid-116/network/external-communications.html)

Hi,

I suppose we should add to the docs, the outgoing comms for ASUP and Software Version Checks.
Primary admin node tries to connect to port 443 of:
support.netapp.com
mysupport.netapp.com

Thanks,
Erik

**Comment by netapp-madkat** [comment]
Hi @estarz,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Principal technical writer
StorageGRID Information Engineering (IE)
