### ISSUE TITLE
Instructions do not properly state the BMC will need to be reconfigured

### ISSUE THREAD

**Issue by anonymous25161** [NetAppDocs/storagegrid-116#45]
The documentation does not properly state that the BMC will need to be reconfigured should the compute node be replaced in step 6, only that the user should check if the IP address is correct. I also do not believe the instructions on how to do so are clear. There is a link below step 6, but you cannot find how to configure the BMC from that link or even the links within those links. Currently there are Knowledge Base articles created to make up for this lack of clear instructions.
Page: [Replace SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/replacing-sg6000-cn-controller.html)

**Comment by netapp-madkat** [comment]
Hi @anonymous25161 

Thank you for bringing this to our attention. We've already updated the upcoming version of the doc site with information about configuring the BMC. I've logged your request against the 11.6 doc site and we'll make the same changes there as time allows.

Thank you for helping us improve the quality of our documentation.

Kathy
Principal technical writer
StorageGRID Information Engineering
