### ISSUE TITLE
SSE Feedback on Remove Fibre Channel HBA

### ISSUE THREAD

**Issue by RSGtheSSE** [NetAppDocs/storagegrid-116#48]
Page: [Remove Fibre Channel HBA](https://docs.netapp.com/us-en/storagegrid-116/sg6000/removing-fibre-channel-hba.html)

the link under "about this task" for monitoring node connections is broken

"See the information about [monitoring node connection states]" (https://docs.netapp.com/us-en/storagegrid-116/monitor/monitor-node-connection-states.html)

that link routes to a 404

**Comment by netapp-madkat** [comment]
Hi @RSGtheSSE,

Oops. Yes, that link is broken. Thank you so much for letting us know. We'll get it fixed as soon as we can.

Thanks,

Kathy Maddox
Principal technical writer
StorageGRID information engineering

**Comment by netapp-madkat** [comment]
The link was fixed. Closed this issue as resolved.
