### ISSUE TITLE
Incorrect link:

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-116#5]
Page: [Verify and upgrade StorageGRID Appliance Installer version](https://docs.netapp.com/us-en/storagegrid-116/sg6000/verifying-and-upgrading-storagegrid-appliance-installer-version.html)

Step 3 is pointing to:
If the appliance has a down-level version of the StorageGRID Appliance Installer, go to the [NetApp Downloads page for StorageGRID](https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab).

It should point to the new Appliance download site:
https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab

regards
Siegfried

**Comment by siegfried-h** [comment]
This will most likely need to be corrected at many other places ans also in the SG5712 and SG5760 documents

**Comment by netapp-madkat** [comment]
Thank you, @siegfried-h. We appreciate that you let us know about this. I've made a note to search for and update the affected links as soon as we can.

**Comment by netapp-madkat** [comment]
Hi Siegfried, 

We have now updated the 11.6 doc site and we added links to the new StorageGRID Appliance download site. Thank you again for your suggestions. We appreciate your help.

Kathy
