### ISSUE TITLE
Please add a topic on Detaching Fabricpool practices

### ISSUE THREAD

**Issue by anumode** [NetAppDocs/storagegrid-116#50]
Page: [Configure StorageGRID for FabricPool: Overview](https://docs.netapp.com/us-en/storagegrid-116/fabricpool/index.html)

**Comment by netapp-madkat** [comment]
Hi @anumode 

Thank you for your request. I've submitted a feature request to add information like this to our doc site. In the meantime, it would be very helpful if you could provide any specific details about what kind of information you're looking for. Without revealing any sensitive details, can you describe the use case for detaching FabricPool and how it was resolved? 

Thank you again for helping us to improve our documentation,

Kathy Maddox
Principal technical writer
StorageGRID information engineering

**Comment by netapp-madkat** [comment]
Hi @anumode, 

This issue has been resolved. Please see https://docs.netapp.com/us-en/storagegrid-117/fabricpool/remove-fabricpool-data.html for the new instructions for removing FabricPool data from StorageGRID.

Thanks,

Kathy
