### ISSUE TITLE
Potential unnecessary step leading to confusion 

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#51]
Page: [Shut down SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/shutting-down-sg6000-cn-controller.html)

Step 1 in the shut down procedure suggests the node must be in maintenance mode before shutting down the node (When the appliance has been placed maintenance mode, shut down the SG6000-CN controller:), however that's not necessary needed for the shut down.

If we look on the power on procedure (https://docs.netapp.com/us-en/storagegrid-116/sg6000/powering-on-sg6000-cn-controller-and-verifying-operation.html), it doesn't mention removing node from maintenance mode, which suggests it is not expected that the node was necessarily in maintenance mode. 

Since maintenance mode is not necessary step for the shut down procedure, I would like to suggest removing step 1.

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp - Thanks for your feedback. I'll verify and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
HI @ahmadm-netapp - We have to removed the requirement to be in maintenance mode to Shut down a SG6000-CN controller from the documentation.
Thanks again for bringing this issue to our attention.
