### ISSUE TITLE
Is it possible to create itemized documents instead of one, large, master document?

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-116#52]
Page: [Place appliance into maintenance mode](https://docs.netapp.com/us-en/storagegrid-116/sg5700/placing-appliance-into-maintenance-mode.html)

The Net2 team received the following feedback from one of our ASEs:
Better Action Plan for StorageGrids. The whole  500 page manual is tough to comprehend.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, thanks for your feedback. I'll look into this and get back to you as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2 - We'll forward your feedback to the NetApp tools team about improving the PDF layout for the doc site. Also, in case you're not aware, below is a screenshot showing how you can create section level PDFs. I hope this helps:
1. In the sidebar, select the first child topic under the section heading.
2. Expand the *Available PDFs* options to publish the PDF.

![image](https://github.com/NetAppDocs/storagegrid-116/assets/77334475/a70b9d49-f8fe-4262-bda3-f10f2f598a1e)
