### ISSUE TITLE
Clarify which method uses KMS

### ISSUE THREAD

**Issue by vardhanv** [NetAppDocs/storagegrid-116#53]
Page: [Review StorageGRID encryption methods](https://docs.netapp.com/us-en/storagegrid-116/admin/reviewing-storagegrid-encryption-methods.html)

I believe only node encryption uses KMS managed keys. The others all have StorageGRID managed keys. The table should clarify that.

**Comment by netapp-pcarriga** [comment]
Hi @vardhanv - Thank you for your feedback. I'll follow up with you via email for some more context on this change. I hope this suits!
