### ISSUE TITLE
Spellcheck needed

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/storagegrid-116#54]
Page: [Guidelines for adding object capacity](https://docs.netapp.com/us-en/storagegrid-116/expand/guidelines-for-adding-object-capacity.html)

![image](https://github.com/NetAppDocs/storagegrid-116/assets/16622642/fa581e3d-8c61-4398-8894-a7a32a74837e)

**Comment by netapp-pcarriga** [comment]
Thank you @scaleoutsean. I'll get this typo corrected as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean - We've corrected this typo in the documentation. Thanks again for bringing this to our attention.
