### ISSUE TITLE
Page spelling correction needed

### ISSUE THREAD

**Issue by isxlow** [NetAppDocs/storagegrid-116#61]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/index.html

### Page title

StorageGRID 11.6 Documentation

### Summary

Spelling error.

NNetApp® StorageGRID® is a software-defined

Note that Netapp has an extra N

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @isxlow, thank you for highlighting this typo which we have now corrected.
