### ISSUE TITLE
Update procedure to remove maintenance mode step

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#63]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/sg100-1000/replacing-fan-in-services-appliance.html

### Page title

Replace fan in services appliance

### Summary

Step 1 in the document suggests the node needs to be placed in maintenance mode: "When the appliance has been placed maintenance mode, shut down the appliance.". 

This step is not needed and it prolongs the procedure. 11.7 docs does not mention maintenance mode.

Is it possible to update the procedure for 11.6 to remove maintenance mode?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Discuss at meeting tomorrow. Does this need to be updated in the docs ?

**Comment by netapp-maireadn** [comment]
Hi @ahmadm-netapp,
Thank you very much for raising this issue. I'm working closely with the StorageGrid team to establish how to proceed as regards updating the documentation.
