### ISSUE TITLE
For Node clone source and destination needs to be on the same PGE version. Docs states only update

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-116#64]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/maintain/appliance-node-cloning-procedure.html

### Page title

Clone appliance node

### Summary

For Node clone source and destination needs to be on the same PGE version. Docs states that the replacement appliance may need to be upgraded. But it is also possible that it needs to be downgraded. Hance I suggest the following change:

From:
You have verified that the StorageGRID Appliance Installer version on the replacement appliance matches the software version of your StorageGRID system, upgrading the StorageGRID Appliance Installer firmware, if necessary.

To:
You have verified that the StorageGRID Appliance Installer version on the replacement appliance matches the software version of your StorageGRID system, upgrading or downgrading the StorageGRID Appliance Installer firmware, if necessary.

regards
Siegfried

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Hi @siegfried-h 
Thank you for taking the time to provide feedback. I will look into your suggestion, and update the documentation accordingly.

**Comment by netapp-maireadn** [comment]
Hi @siegfried-h 
Your suggested wording will be included in the next release of StorageGrid.
I'm closing this issue now.
Many thanks for your feedback.
Mairead
