### ISSUE TITLE
Updating service appliance docs to include SG100/SG1000

### ISSUE THREAD

**Issue by brandsofchase** [NetAppDocs/storagegrid-116#66]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-services-appliance.html

### Page title

Replace services appliance

### Summary

It is difficult to search for hardware replacement doc on SG100/SG1000 because none of the titles include the product model. I'd like to request that the product model be included in the title for the following documentation. Something similar to the SG6000 models

SG6000 doc example
Replace one or both power supplies in the SG6000-CN controller
https://docs.netapp.com/us-en/storagegrid-117/sg6000/replacing-one-or-both-power-supplies-in-sg6000-cn-controller.html

Docs that could be updated 
Replace one or both power supplies in the services appliance - Current title
Replace one or both power supplies in the SG100/SG1000 services appliance - Updated title
https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-one-or-more-power-supplies-in-services-appliance.html

Replace fan in services appliance - Current title
Replace fan in the SG100/SG1000 services appliance - Updated title
https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-fan-in-services-appliance.html

Replace drive in services appliance - Current title
Replace drive in the SG100/SG1000 services appliance - Updated title
https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-drive-in-services-appliance.html

Replace services appliance - Current title
Replace the SG100/SG1000 services appliance - Updated title
https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-services-appliance.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @brandsofchase, thanks again for this suggestion. At this time we won't update StorgeGRID 11.7 documentation and earlier versions but this recommendation will be considered for inclusion in future versions. Thanks for understanding.
