### ISSUE TITLE
Inclusion of parameter for FIPS enabled secure drives

### ISSUE THREAD

**Issue by kaushikamitra** [NetAppDocs/storagegrid-116#67]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/sg5700/replacing-e2800-controller.html

### Page title

Replace E2800 series storage controller in the SG5700

### Summary

Under section, About this task

If all drives are secured, you have reviewed the steps in the simplex E2800 series controller replacement procedure, which include downloading and installing E-Series SANtricity Storage Manager from the NetApp Support Site and then using the Enterprise Management Window (EMW) to unlock the secured drives after you have replaced the controller.

There needs to be a step included to Power Off the shelf before replacing controller as this can lead to issue described in ECD-16248. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Thanks @kaushikamitra for providing this feedback.
We'll look into this as soon as possible.
Kind Regards,
Mairead

**Comment by netapp-pcarriga** [comment]
Hi @kaushikamitra, we've added steps to power on and off the controller shelf in later versions of the StorageGRID documentation, which you can review using the following link:
 https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/replacing-e2800-controller.html#step-2-take-the-controller-offline
At this time, we are not making this update to version 11.6 of the documentation site. Thanks for understanding, and thanks again for your recommendation and helping us improve our customer documentation.
