### ISSUE TITLE
Add more details about older storagegrid images

### ISSUE THREAD

**Issue by sndstone** [NetAppDocs/storagegrid-116#76]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html

### Page title

Linux: Install the RPM or DEB package on all hosts

### Summary

Hello team,

I wanted to ask if you could add more details regarding older images on bare metal host os'es since it says : "Do not remove the existing packages." while this is true for the current version any older once could be removed.
This causes some cutomers to leave packages from Sgrid 11.1 all the way up to 11.8 filling up the main drive of the host server.
Could you add more details about this for the current supported releases?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Hi @sndstone 
Thanks for your feedback.
I will investigate and get back to you as soon as possible.

**Comment by sndstone** [comment]
Hi Mairead,

I have attached my NetApp email since I only have a person GitHub account. If you need anything let me know.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by netapp-maireadn** [comment]
Thanks for that Bryan

**Comment by netapp-maireadn** [comment]
I'm closing this issue now. I created a jira which tracks this: SGRIDDOC-56.
