### ISSUE TITLE
The default package manager for RHEL 8 or later has changed from yum to DNF

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/storagegrid-116#81]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/rhel/installing-storagegrid-webscale-host-service.html

### Page title

Install StorageGRID host services

### Summary

The default package manager for RHEL 8 or later has changed from yum to DNF, however, rhel_install_from_repo.yml file which is contained in storagegrid installer (e.g.StorageGRID-Webscale-11.6.0-RPM-20220210.0232.8d56cfe.tgz) is still using yum as package manager.

![rhel_install_from_repo](https://github.com/user-attachments/assets/0cf74c0e-d12c-4dcf-81e9-26a787b5281e)

This caused installation fails as below

TASK [storagegrid : Install StorageGRID from YUM repository] ********************************************************************************************************************************************************************************
fatal: [Non-Primary-Admin-Node]: FAILED! => {"changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
  
details error logs:
[python2.install.error.txt](https://github.com/user-attachments/files/16389796/python2.install.error.txt)
[python3.install.error.txt](https://github.com/user-attachments/files/16389797/python3.install.error.txt)

It has been confirmed that edited the rhel_install_from_repo.yml file as below can workaround the error.
But customer requested Netapp officially verified documents. So please help to confirm and update the doc ASAP. Thanks!

- name: Install StorageGRID from YUM repository
    # yum:
    dnf:   <<<<<<<<<<<<<<<<
      name: "{{ pkg_list }}"
      state: latest
    vars:
      pkg_list:
        - "StorageGRID-Webscale-Images-{{ release_version }}"
        - "StorageGRID-Webscale-Service-{{ release_version }}"
    register: installed
    notify: start storagegrid
  tags: install

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by zhuolin-shen** [comment]
The yml file's format becomes strange so attached the capture for clarification:
![Screenshot 2024-07-26 184304](https://github.com/user-attachments/assets/4bd7367e-0214-489c-b126-440a3dff0e8f)

**Comment by netapp-pcarriga** [comment]
HI @zhuolin-shen, thank you for bringing this to our attention. I'm looking into this and will update you here.

**Comment by zhuolin-shen** [comment]
Thank you for your reply.  I will look forward to your update.
Additional query from customer, could you please also help to confirm whether the workaround is valid without any side effect?

**Comment by netapp-pcarriga** [comment]
Hi @zhuolin-shen, I've opened  SGRIDDOC-95 to track this request and added you as a w watcher.
